// <auto-generated />
using System;
using GestionStock.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionStock.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("GestionStock.API.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fournisseur")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Prix")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeuilAlerte")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Produits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categorie = "Électronique",
                            DateAjout = new DateTime(2026, 3, 23, 21, 45, 31, 384, DateTimeKind.Utc).AddTicks(776),
                            Fournisseur = "TechPro",
                            Nom = "Câble USB-C",
                            Prix = 9.99m,
                            SeuilAlerte = 10,
                            Stock = 142
                        },
                        new
                        {
                            Id = 2,
                            Categorie = "Électronique",
                            DateAjout = new DateTime(2026, 3, 23, 21, 45, 31, 384, DateTimeKind.Utc).AddTicks(783),
                            Fournisseur = "TechPro",
                            Nom = "Hub HDMI",
                            Prix = 29.99m,
                            SeuilAlerte = 5,
                            Stock = 3
                        },
                        new
                        {
                            Id = 3,
                            Categorie = "Périphériques",
                            DateAjout = new DateTime(2026, 3, 23, 21, 45, 31, 384, DateTimeKind.Utc).AddTicks(785),
                            Fournisseur = "Vision+",
                            Nom = "Webcam HD",
                            Prix = 49.99m,
                            SeuilAlerte = 5,
                            Stock = 0
                        },
                        new
                        {
                            Id = 4,
                            Categorie = "Périphériques",
                            DateAjout = new DateTime(2026, 3, 23, 21, 45, 31, 384, DateTimeKind.Utc).AddTicks(786),
                            Fournisseur = "Vision+",
                            Nom = "Souris sans fil",
                            Prix = 24.99m,
                            SeuilAlerte = 8,
                            Stock = 38
                        },
                        new
                        {
                            Id = 5,
                            Categorie = "Périphériques",
                            DateAjout = new DateTime(2026, 3, 23, 21, 45, 31, 384, DateTimeKind.Utc).AddTicks(788),
                            Fournisseur = "KeyMaster",
                            Nom = "Clavier mécanique",
                            Prix = 89.99m,
                            SeuilAlerte = 5,
                            Stock = 12
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
